server:
  port: 8080
  error:
    include-stacktrace: on-param
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: dev
  application:
    name: api
  datasource:
    url: jdbc:postgresql://db:5432/api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      data:
        web:
          pageable:
            default-page-size: 10
            max-page-size: 100
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migrations
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

