server:
  port: 8080
  error:
    include-stacktrace: on-param
  servlet:
    context-path: /api/v1

spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://db:5432/api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
