services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  api:
    container_name: api
    working_dir: /home/java/app
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports: 
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: always

networks:
  db:
    driver: bridge

volumes:
  db:
  